woowacourse-teams/2025-bom-bom

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/domain/Article.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/ContinueReading.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Role.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/WeeklyGoal.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/controller/NewsletterController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/Category.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/Newsletter.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/NewsletterDetail.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/NewsletterDetailRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/NewsletterRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/service/NewsletterService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/subscribe/domain/Subscribe.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/newsletter/service/NewsletterServiceTest.java

전체 뉴스레터 목록 조회 API를 구현했습니다.
뉴스레터 추천 페이지에서 필요합니다.
JPA의 쿼리 메서드로 구독자 수 (desc), 이름(asc)로 정렬된 데이터를 받습니다.
그리고, 초기에는 셔플 후에 리턴하기로 정했기 때문에 셔플 후에 controller로 리턴하도록 했습니다.
예외 발생 경우가 생각나지 않아 예외 처리를 하지 않았습니다.
테스트가 충분한지 검토해주시면 감사드리겠습니다.

[BE][BOM-23] feat: 뉴스레터 목록 조회 API 구현

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/controller/MemberController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/TodayReading.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/response/ReadingInformationResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/response/TodayReadingResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/response/WeeklyReadingResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/repository/ContinueReadingRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/repository/TodayReadingRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/service/MemberServiceTest.java

- 연속 읽기, 오늘의 진행 현황, 주간 목표 조회를 조회하는 API를 구현합니다.
- '오늘의 뉴스레터' 페이지에서 사용됩니다.
- 오늘의 읽기 현황 저장을 위해 `TodayReading` 테이블이 추가되었습니다.
- 이후에는 `ContinueReading`, `TodayReading`, `WeeklyReading`을 조회해서 dto 가공만 하면 됐습니다.
- `@RequestParam`로 받는 `memberId`는 임시방편입니다.

[BE][BOM-17] feat: 연속 읽기 & 오늘의 진행 현황 & 주간 목표 조회 API 구현

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCategoryStatisticsResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCountPerCategoryResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/service/ArticleServiceTest.java

- 카테고리 별 아티클 개수를 조회하는 API를 구현합니다.
1. `memberId`가 유효한지 검증합니다.
2. 해당 회원의 전체 아티클 개수를 count 합니다.
3. 모든 `category`를 불러오고, 각 카테고리를 순회하며 아티클 개수를 조회해 dto에 담습니다.
- `articleRepository.countAllByCategoryIdAndMemberId(category.getId(), memberId)`를 JPQL로 작성했습니다.
- JPA method로만 구성할 경우,
1. 모든 `category`를 조회합니다.
2. 회원의 모든 `article`을 조회합니다.
3. 각 카테고리를 순회하며, `article`들 중 `newsletter`의 `categoryId`가 현재 `categoryId()`와 같은 것들을 필터링 합니다. 
-> 매 article 마다 newsletter 조회 query 발생
: `(카테고리 개수 * 아티클 개수)`번의 추가 쿼리
- 따라서 JPQL로 개수 조회 쿼리를 작성하는 것이 더 효율적일 것이라고 판단했습니다. 
- 네이밍은 언제나 어렵네요.. 메서드나 클래스 네이밍 추천 있으면 부탁드립니다! (특히 controller, service 메서드 네이밍)
- 더 효율적인 로직 있다면 피드백 부탁드립니다-

[BE][BOM-87] feat: 카테고리 별 아티클 개수 조회 API 구현

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/Newsletter.java

뉴스레터 중에 발신 이메일 길이가 30자가 넘는 곳이 있습니다.
다 담아야 할 것 같아요
- email length를 30 -> 60으로 넉넉하게 늘립니다.
- `ddl-auto` 설정이 `update`로 되어있지만, 현재 더미 데이터가 존재하므로 코드만 바꾼다고 테이블의 제약 조건 변경이 반영되진 않습니다.
- 따라서 RDS에서 직접 아래 쿼리도 실행했습니다.
```sql
ALTER TABLE newsletter
MODIFY COLUMN email VARCHAR(60) NOT NULL;
```

[BE][BOM-101] fix: 뉴스레터 이메일 길이 제한 증가

---

frontend/src/utils/date.test.ts
frontend/src/utils/math.test.ts

- 유틸 테스트 date, math에서 테스트가 깨지는 현상 발생
- date: 로컬이 아닌 UTC 타임존 기준으로 테스트를 실행함
- math: 함수 로직의 변경이 테스트 코드에 반영되지 않음
- date: 로컬 타임존 기준으로 날짜를 계산하도록 수정
- math: 함수 로직 변경 반영

[FE][BOM-152] test: 테스트가 깨지는 현상 수정

---

frontend/src/routes/storage.tsx

검색 api 요청에 걸려있는 디바운싱 타임 수정
- 검색어가 변경될 때 실시간으로 요청을 보내면서, 과도한 요청이 오고 있다는 백엔드 측의 피드백을 받음
- 디바운스 시간을 300ms 에서 500ms로 변경

[FE][BOM-160] fix: 디바운싱 타임 수정

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/resolver/LoginMemberArgumentResolver.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupEvent.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupListener.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberSignupListenerTest.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/service/ReadingServiceTest.java

로그 삭제보다 읽기 정보 초기화 비중이 커져서 브랜치 이름을 바꿨더니, 기존 PR에 반영이 안돼서 새로 PR 올립니다. merge후 기존 pr은 close 하겠습니다.
[수정범위](https://github.com/woowacourse-teams/2025-bom-bom/pull/102/files/5e3592f52ab4119df695620c5179175d7da5cb7c..56f5bd28b0994de7a610613c37349f6ccf7ea70d)
[기존PR](https://github.com/woowacourse-teams/2025-bom-bom/pull/93)
회원가입 시 읽기 정보 초기화 방식 수정
UX 개선
회원가입과 같은 트랜잭션에서 수행하던 읽기 정보 초기화를 동기 이벤트 리스너 기반으로 수정하였습니다.
테스트 방식에 대해서 생각해봐야 할 것 같습니다. `SpringBootTest`에서 `@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)`이 반영되지 않는 문제가 있어서, 일단 `ReadingServiceTest`만 작성하였습니다.

[BE][BOM-164] feat: 회원가입 시 읽기 정보 초기화

---

frontend/src/apis/articles.ts
frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.tsx
frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
frontend/src/routes/_bombom/articles.$articleId.tsx
frontend/src/routes/_bombom/index.tsx

- 뉴스레터 읽기 페이지 하단에 안읽은 뉴스레터 클릭 기능 추가
- 뉴스레터 카드를 Link 태그로 변경하였습니다.
- 읽음 처리한 이후에 오늘 안읽은 뉴스레터 리스트가 갱신되지 않는 문제가 있어서, invalidateQuery에 추가했습니다.

[FE][BOM-218] feat: 오늘 안읽은 뉴스레터 클릭 기능 추가

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/CustomArticleRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/CServerErrorException.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/GlobalExceptionHandler.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupListener.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/ScorePolicyConstants.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/controller/PetController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Pet.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Stage.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/dto/PetResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/event/AddArticleScoreEvent.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/event/AddArticleScoreListener.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/PetRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/StageRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberSignupListenerTest.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/event/AddArticleScoreListenerTest.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/service/PetServiceTest.java

- 키우기에 필요한 기능들을 구현합니다.
- 습관형성을 위함입니다.
- `Pet` : 사용자의 키우기 정보를 저장합니다.
- `Stage` : 각 레벨 별 정보를 저장합니다.
- 해당 PR이 merge 되면 추후에 수기 작업으로 데이터를 삽입할 예정입니다.
- enum으로 관리할까도 고민했지만, 현재 키우기에 대한 스펙이 명확하지 않아 테이블로 관리하는게 편리할 것이라고 판단했습니다.
1. `/members/me/pet` : 회원의 키우기 정보를 조회합니다.
2. `/members/me/attendance` : 회원이 '출석하기' 버튼을 통해 출석 점수를 받습니다.
3. 아티클 읽음 시 키우기 점수 추가 이벤트 등록 : 키우기 정책에 따라 `아티클 다읽음 처리 API` 호출 시, 읽음 키우기 점수를 판별하고 추가하는 이벤트를 등록합니다.
- 정책은 아래와 같습니다. 
```text
- 점수 기준
- 하나의 아티클을 읽을 때 → 10점
- max : 최대 3개
- 연속 읽기 날짜
- 일주일 이상 읽기 시작하면 아티클 당 가중치 +5점씩 (총 아티클 당 점수는 15점 됨)
- 출석
- 매일 5점
```
4. 회원가입 시 `MemberSignUpEvent`에 `Pet`을 등록하는 로직을 추가했습니다. 
- 점수가 추가되는 이벤트들에 대해 레벨업 처리를 해주는 이벤트 등록은 다른 PR로 올라올 예정입니다.
1. 이벤트 리스너를 직접 도입해보는건 처음인데, 점수에 대한 이벤트라고 생각해서 `AddArticleScoreEvent`를 `pet/event` 패키지로 두었는데 어색하진 않은지 피드백 받고싶습니다!
2. …

[BE][BOM-202] feat: 키우기 관련 기능 구현

---

frontend/src/components/PageLayout/PageLayout.tsx
frontend/src/components/Tab/Tab.tsx
frontend/src/components/Tabs/Tabs.tsx
frontend/src/pages/storage/components/CategoryFilter/CategoryFilter.tsx
frontend/src/pages/storage/components/QuickMenu/QuickMenu.tsx
frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
frontend/src/routes/_bombom/storage.tsx

- 모바일 디바이스에서 카테고리 세로로 보여주는 건 `useMediaQuery` 머지되면 수정하도록 하겠습니다.
- 현재는 하드코딩해서 `1024px`을 기준으로 배치가 바뀌는데, theme에 breakpoint가 추가되면 수정하겠습니다.
- 1024px 기준으로 작다면(모바일~태블릿) 이미지와 같이 좌우배치 & 상단에 올라오고, 크다면(PC) 상하배치 & 왼쪽에 배치됩니다.

[FE][BOM-194] feat: 보관함 페이지 반응형

---

frontend/src/components/Header/Header.tsx

[FE][BOM-311] fix: 모바일 하단 nav 버튼 패딩 벗어나는 문제 해결

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleControllerApi.java

특정 아티클의 하이라이트 목록을 조회하는 API에 swagger 설정을 추가합니다.
프론트에게 정보를 제공하기 위함입니다.
아티클 하이라이트 목록 조회 API에 대해 Api 인터페이스 추가 및 override를 추가했습니다.

[BE][BOM-334] feat: 아티클 하이라이트 목록 조회 swagger 추가

---

frontend/src/components/FloatingActionButton/FloatingActionButton.tsx
frontend/src/components/Header/Header.tsx
frontend/src/styles/theme.ts

- 태블릿, 모바일 환경에서 플로팅 버튼이 하단 네비게이션과 겹치는 문제 수정
-  태블릿, 모바일 환경에서 플로팅 버튼이 하단 네비게이션 위로 침범하는 문제가 있었음.
- 플로팅 버튼 배치 조정

[FE][BOM-324] 플로팅 버튼 바텀 내부랑 겹치는 문제

---

frontend/src/components/Badge/Badge.tsx
frontend/src/pages/recommend/components/NewsletterDetail/NewsletterDetail.tsx

- 모달창의 홈페이지 링크 위치 변경
- 홈페이지 링크를 아이콘으로 간소화
- 지난 뉴스레터 링크 위치 변경 (개요 설명 위 → 아래)
- 추후 링크 대신, 데이터를 직접 패칭해올 것을 고려함
- 기타 전반적인 gap, font size 변경
**[PC, 태블릿]**
**[모바일]**

[FE][BOM-346] 모달 홈페이지 링크 위치 변경

---

frontend/src/components/Header/Header.tsx
frontend/src/components/PageLayout/PageLayout.tsx
frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
frontend/src/routes/_bombom/index.tsx
frontend/src/routes/_bombom/recommend.tsx
frontend/src/routes/_bombom/storage.tsx
frontend/src/styles/theme.ts

- 헤더 및 하단 네비게이션 높이를 전역 스타일로 관리
- 각 페이지의 패딩을 PageLayout에서 일괄적으로 관리하도록 리팩토링 (통일성, 유지보수 용이성 고려)
- 페이지 반응형 디자인 수정
[before - after]
<br>
[before - after]

[FE][BOM-354] 뉴스레터 보관함 반응형 디자인 수정

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/MonthlyReadingRankResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingRepository.java

이달의 독서왕 쿼리를 수정했습니다.
500 에러가 났습니다.
테스트에서는 문제 없어서 괜찮은 줄 알았습니다..
EC2에 직접 들어가서 쿼리를 실행시켜보았는데요.
쿼리에서 CAST가 INT가 H2에서는 가능한데, MySQL에서는 동작하지 않는 문제를 발견했습니다.
MySQL에서는 INT가 아니라, SIGNED, UNSIGNED로 가능하다는 것을 알았습니다.
이 또한, EC2에 들어가서 직접 쿼리를 실행시켜 결과가 제대로 나오는 것을 확인했습니다.

[BE][BOM-358] fix: 이달의 독서왕 쿼리 수정

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/CustomOAuth2UserService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/ErrorDetail.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/resolver/LoginMemberArgumentResolver.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/repository/MemberRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/scheduler/MemberCleanupScheduler.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/service/MemberServiceTest.java

- 회원 탈퇴 기능
- 탈퇴시 soft delete
- 탈퇴 후 1년 지난 회원은 DB에서 삭제
- 민감한 데이터 보관
- `Member` 엔티티에 `deletedAt` 필드 추가
- `@SQLRestriction("deleted_at IS NULL")` 어노테이션을 통해 DB 조회 시에 deleted_at이 NULL인 회원(탈퇴 x) 만 조회하도록 함
- 스케줄러를 통해 매일 자정에 탈퇴 후 1년 지난 회원 hard delete 함
- 탈퇴를 `Withdraw`로 사용하고, 있는데 더 적절한 네이밍 있을까요
- `deletedAt`을 `BaseEntity`나 다른 상위 엔티티의 필드로 만들지 않아도 될까요

[BE][BOM-343] feat: 회원 탈퇴 및 soft delete 기능 구현

---

frontend/src/components/PetCard/PetCard.tsx

- 펫 카드의 경험치 바와 출석체크 버튼 사이의 간격 조정
**[before - after]**

[FE][BOM-366] 펫 카드 레이아웃 조정

---

frontend/src/components/PageLayout/PageLayout.tsx
frontend/src/components/RequireLoginCard/RequireLoginCard.tsx

- 로그인 요청 카드의 반응형 디자인 추가
- PageLayout의 Container에 100dvh 추가 → 모바일 환경에서 기기 UI의 동적인 변화에 상관없이 레이아웃을 유지할 수 있도록 추가함
- 100dvh, 100vh, 100% 차이점이 궁금하신 분은 제게 오시면 예시 화면 보여드릴게요
https://github.com/user-attachments/assets/da48bd59-4878-47f6-a5cd-956007a53ae7
- 로그인 요청 카드의 모바일 뷰 개선 목적
useDeviceType을 이용하여 환경 타입에 따라 조건부로 스타일링 수행

[FE][BOM-364] 로그인 요청 카드의 반응형 디자인 추가 

---

frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx

- 가이드 메일 읽기 페이지일 때, 북마크 버튼이 제거되도록 함
https://github.com/user-attachments/assets/3d2113d2-2192-41ce-bb53-99351d97d4fe
- 가이드 메일에서는 북마크 기능이 동작하지 않음에도 버튼이 표시되는 문제가 있었음.
- useLocation으로 현재 페이지의 pathname 추출
- pathname이 가이드 읽기 페이지 경로에 해당하는지 확인
- 가이드 메일이면 북마크 버튼을 렌더링하지 않음

[FE][BOM-367] 모바일 환경 가이드의 북마크 제거

---

frontend/src/components/PetCard/PetCard.constants.ts
frontend/src/components/PetCard/PetCard.tsx

- 최대 레벨인 펫의 경험치 UI 변경
- 경험치 바(progress bar)는 100%로 채워짐
- 경험치 비율(%) 대신, 점수(점)를 표시
- 기존에는 펫이 최대 레벨일 때 경험치 UI에 변화가 없었음
- 출석체크를 하거나 아티클을 읽어도 경험치에 변화가 없어, 혼란 초래
- 사용자의 동기부여를 유지할 수 있는 요소가 없음
최대 레벨 펫의 경험치 UI를 개선

[FE][BOM-379] 최대 레벨 펫의 경험치 UI 수정

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/domain/MonthlyReading.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingRepository.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
backend/bom-bom-server/src/main/resources/db/migration/V1.21__monthly_reading_change_column_name.sql

MonthlyReading의 rank 컬럼명을 rankOrder로 수정했습니다.
rank가 예약어인데도 불구하고 백틱으로 회피해서 쓰고 있었는데, 문제가 계속 생겼습니다.
그래서 아예 rankOrder로 수정했습니다.
테이블의 컬럼명만 변경하고, 프론트에게 주는 컬럼명은 그대로 rank입니다.

[BE][BOM-389] fix: MonthlyReading의 rank 컬럼명 수정

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/AppleClientSecretSupplier.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthControllerApi.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/request/NativeLoginRequest.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/AppleOAuth2Service.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/CustomOAuth2UserService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/GoogleOAuth2LoginService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/IdTokenValidator.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/OAuth2LoginService.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SecurityConfig.java

모바일 앱에서 애플 원탭 로그인 API를 구현했습니다.
모바일 앱에서는 원탭 로그인이 편리하므로.
원탭 로그인을 위해서는 기존 방식과는 달리 클라이언트 측에서 애플/구글에 요청을 하고 인증 정보를 서버로 넘겨 받아야 합니다.
그것을 위해 POST api로 인증 정보를 받습니다. 이후에 인증 정보를 통해 애플/구글로 accessToken 발급 요청을 넘기고, 기존 회원일 경우 로그인, 신규 회원일 경우 회원가입을 수행하는 것은 동일합니다.
추가로, 탈퇴 시에 토큰 철회를 위해서는 요청 Token에 client-id가 들어가야 합니다. 그런데, client-id가 웹에서는 Service-ID이지만, 앱에서는 App-ID를 사용합니다, 그래서, 이 부분도 분기처리를 하였습니다.

[BE][BOM-423] feat: 모바일 앱에서 애플 원탭 로그인 API 구현

---

backend/bom-bom-server/build.gradle.kts
backend/bom-bom-server/src/main/java/me/bombom/BomBomServerApplication.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/ShedLockConfig.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/scheduler/ReadingScheduler.java
backend/bom-bom-server/src/main/resources/db/migration/V3.00__create_shedlock_table.sql

ShedLock 라이브러리로, 둘 중 하나의 EC2만 스케줄러를 실행하도록 하였습니다.
두개의 EC2가 모두 스케줄러를 실행하여 이달의 독서왕 구하는 쿼리에서 데드락이 발생했습니다.
[노션에 정리했습니다.](https://luminous-november-24d.notion.site/2712380f6fa58062a0d3f235473ca82b?source=copy_link)

[BE][BOM-433] fix: 두개의 인스턴스에서 스케줄러가 모두 실행되는 문제 해결

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/request/MemberSignupRequest.java

회원가입시 받는 nickname, email 정규식을 수정했습니다.
사용자 요청으로 인해
닉네임은 인스타그램 스타일로, 이메일은 Gmail 스타일로 했습니다.
닉네임 검증
•	인스타그램 스타일을 참고하여 정규식을 설계했습니다.
•	규칙: 영문자와 숫자로 시작/끝나야 하고, 중간에는 영문자, 숫자, _, .만 허용합니다.
•	연속된 점(..)은 허용하지 않도록 조건을 추가했습니다.
이메일 검증
•	Gmail 스타일을 참고했지만, + 문자는 허용하지 않았습니다.
•	규칙: 영문자/숫자로 시작하고 끝나야 하며, 중간에는 영문자, 숫자, ., _, -만 허용합니다.
•	연속된 점(..)은 허용하지 않도록 조건을 추가했습니다.
•	도메인은 @bombom.news 로 고정했습니다.

[BE][BOM-440] fix: 회원가입시 받는 nickname, email 정규식 수정

---

frontend/src/routes/_bombom.tsx

첫 페이지에서만 인증을 확인합니다.
기존에 `await queryClient.fetchQuery(queries.me());` 앞에 if문으로 `isFirstVisit`을 넣으려했지만, 그러한 경우 첫 방문 이외에 recommend이외의 페이지에 이동하면 더이상 errorComponent(RequireLoginCard 컴포넌트)를 보여주지 못합니다. 그래서 `queryClient.getQueryData(queries.me().queryKey)`로 캐싱된 쿼리에 있는 사용자 정보를 불러오도록 수정했습니다.

[FE][BOM-437] 첫 페이지에서만 인증 확인

---

frontend/src/routes/_bombom.tsx

- user_id를 로그인 하지 않았을 때도 설정해주었는데,
- 기존 사용자가 서비스에 진입하여 로그인을 하게 될 경우 활성 사용자가 3이 찍히는 문제가 있었습니다.
- 지금 추측하기로는
- 첫 진입 시, user_id 세팅 전이기 때문에 client_id로 잡힘
- 로그인 상태를 확인하고 로그인하지 않았기 때문에, 'guest'라는 user_id로 잡힘
- 로그인을 하게 될 경우, 로그인 사용자의 user_id로 세팅되어 잡힘
- 그래서 로그인하지 않았을 경우는 user_id를 'guest'로 하지 않아 우선 2만 잡히도록 수정하였습니다.

[FE][BOM-445] GA user id 세팅 오류 해결

---

backend/mail-server/src/main/java/news/bombomemail/email/extractor/HtmlTextExtractor.java

- style 태크가 전체 삭제되는 에러 수정
`Jsoup.clean()` 메서드를 잘 못 사용함
기존 코드
```java
Jsoup.clean((String) part.getContent(), Safelist.basic());
```
- `Jsoup.clean(html, safelist)`은 입력 HTML을 파싱한 뒤, safelist에 허용된 태그·속성만 남기고 나머지를 모두 제거합니다. 즉 HTML을 “살균”해서 XSS나 악성 스크립트를 막는 용도
- `Safelist.basic()`은 기본적인 문단/링크/리스트 정도만 허용하고 <style> 태그, style 속성은 전부 잘라냅니다. 그래서 이전 코드에서 `Jsoup.clean(..., Safelist.basic())`을 쓰면 CSS가 다 사졌던 것 입니다.

[BE][BOM-482] fix: html 파싱 오류 해결

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/NativeLoginResponse.java
backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/request/NativeLoginRequest.java

앱 로그인 시 유니크한 닉네임, 이메일 넘겨주도록 구현했습니다.
앱 로그인 시에는 웹 로그인과 다르게, 애플에게 인증 정보를 요청하는 첫 요청을 앱에서 수행하기 때문에, 다른 구현이 필요합니다.
사용자의 인증 정보에 담긴 email과 nickname을 받아 기존 `UniqueUserInfoGenerator`를 통해 유니크한 값을 생성합니다.
빠르게 구현하고, 리팩터링은 추후에 진행하겠습니다.

[BE][BOM-525] feat: 앱 로그인 시 유니크한 닉네임, 이메일을 클라이언트에게 넘겨주도록 구현

---

backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
backend/bom-bom-server/src/main/resources/db/migration/V6.7.0__remove_member_deleted_at_field.sql

회원 테이블의 deleted_at 필드를 제거합니다.
`withdrawn_member`로 데이터가 이전되고, `member` 테이블에 `deleted_at` 필드가 필요없어지게 되기 때문입니다. 
- 기존에 `@SQLRestriction`이랑 `@SQLDelete`를 쓰고 있었어서, 단순히 필드만 제거해줘도 처리 가능했습니다. 
- flyway는 기존에 `deleted_at`이 NULL이 아닌 회원 (탈퇴처리 되어있던 회원)들은 `member` 테이블에서 delete 합니다.
- 이후에 `member` 테이블에서 `deleted_at` 필드를 제거합니다. 
- 현재 탈퇴되어 있던 데이터들을 `WithdrawnMember`로 이전하는 flyway도 작성해야할까 고민입니다.
- DB 확인해보니까 탈퇴한 계정들이 다 내부 개발자들 계정이라 이번에 굳이 이전할 필요가 있을까 싶어서 작성 안했습니다..!
- delete 쿼리라 무섭습니다.. 간단하지만 쿼리 확인 꼭 부탁드려요..

[BE][BOM-517] fix: 회원 테이블 deleted_at 필드 제거
