woowacourse-teams/2025-bom-bom

.gitignore
=> docs: gitignore 파일 수정

frontend/jest.config.cjs, frontend/package-lock.json, frontend/package.json, frontend/public/assets/clock.svg, frontend/src/App.tsx, frontend/src/pages/today/components/ArticleCard.tsx, frontend/src/pages/today/components/ArticleCars.stories.tsx, frontend/src/pages/today/types/article.ts, frontend/src/svg.d.ts, frontend/src/utils/date.test.ts, frontend/src/utils/date.ts, frontend/tsconfig.json
- 아티클 카드 컴포넌트 제작
- (스토리북 제작하지 않아서 App에 확인용으로 컴포넌트 추가해놓았습니다)
- FigJam에 있는 Article 데이터 타입을 ArticleCard props로 넘겨받습니다.
- props로 전달받은 data로 ArticleCard ui를 그립니다.
- props 형태
- (초반이라서) type, util 파일 구조
- svg.d.ts 파일 위치 및 파일명
=> [FE][BOM-38] feat: article component 제작

backend/bom-bom-server/.github/workflow/dev-deploy.yml
=> [BE][BOM-71] chore: ci 파이프라인 구축

backend/bom-bom-server/.github/workflow/dev-deploy.yml
=> [BE][BOM-71] chore: ci 파이프라인 수정

frontend/src/components/SearchInput/SearchInput.stories.tsx, frontend/src/components/SearchInput/SearchInput.tsx, frontend/src/components/icons/ReadingGlassesIcon.tsx
=> [FE][BOM-75] feat: SearchInput component 제작

frontend/src/components/Header/Header.tsx, frontend/src/pages/today/components/ArticleCard.tsx, frontend/src/styles/reset.ts
tanstack router를 이용한 페이지 라우팅을 합니다.
=> [FE][BOM-96] feat: 페이지 라우팅

frontend/package.json, frontend/src/apis/env.ts, frontend/src/main.tsx, frontend/webpack.config.cjs
- msw를 선택적으로 사용할 수 있게 스크립트를 분리하였습니다.
- 기본 `npm run start`는 msw 적용 X
- `npm run start:msw`는 msw 적용 O
=> [FE][BOM-108] feat: enable msw 설정

frontend/src/apis/articles.ts, frontend/src/apis/fetcher.ts, frontend/src/components/Tabs/Tabs.stories.tsx, frontend/src/components/Tabs/Tabs.tsx, frontend/src/mocks/article.ts, frontend/src/mocks/data/mock-articles.ts, frontend/src/pages/storage/utils/getArticleReadStats.ts, frontend/src/pages/today/components/ArticleCard/ArticleCard.stories.tsx, frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx, frontend/src/pages/today/types/article.ts, frontend/src/pages/today/types/category.ts, frontend/src/routes/articles.$articleId.tsx, frontend/src/routes/index.tsx, frontend/src/routes/storage.tsx, frontend/src/utils/date.test.ts, frontend/src/utils/date.ts
- 카테고리, 정렬 기능을 추가합니다.
- 백엔드 데이터를 적용합니다.
=> [FE][BOM-117] feat: category sort filter 기능 추가

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/ArticleDetailResponse.java
아티클 상세 조회 반환값에 isRead 필드를 추가했습니다.
읽음 정보에 따라 사용자에게 보여주기 위해서
=> [BE][BOM-128] fix: 아티클 상세 조회 반환값에 isRead 필드 추가

frontend/src/apis/articles.ts, frontend/src/apis/fetcher.ts, frontend/src/hooks/useThrottle.ts, frontend/src/pages/detail/types/articleDetail.ts, frontend/src/routes/articles.$articleId.tsx, frontend/src/routes/index.tsx, frontend/src/utils/scroll.test.ts, frontend/src/utils/scroll.ts, frontend/webpack.config.cjs
- 스크롤 70% + 읽기 시간 3초 이상일 경우 읽음 처리하는 기능을 추가했습니다.
- 스크롤 이벤트에 throttle을 적용하여 구현
- 스크롤 70% 이상일 때, 현재 시간을 기준으로 페이지에 들어온 시간의 3초 후면 read patch 호출
=> [FE][BOM-119] feat: article read 기능 구현

frontend/src/routes/storage.tsx
=> [FE][BOM-130] feat: category 필터링 name으로 변경

backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/handler/OAuth2LoginSuccessHandler.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SecurityConfig.java
구글 로그인 후 리다이렉트 기능 구현
기존 회원과 신규 회원에 대해서 리다이렉트 구분
일단 프론트 로컬로 리다이텍트 URL 고정시켜뒀습니다.
=> [BE][BOM-131] feat: 구글 로그인 후 리다이렉트 기능 구현

frontend/src/apis/articles.ts, frontend/src/components/SearchInput/SearchInput.stories.tsx, frontend/src/components/SearchInput/SearchInput.tsx, frontend/src/hooks/useDebounce.ts, frontend/src/hooks/useThrottle.ts, frontend/src/routes/storage.tsx
- 아티클 검색 기능을 구현하였습니다.
- 실시간 검색을 도입하여
- SearchInput을 form에서 div로 변경하였습니다.
- callback 함수의 인자로 어떤 것이 들어올지 몰라서 최대한 범용성을 위해 any를 사용하였습니다.
- 이것에 대해서 어떻게 생각하는지 의견 주시면 감사하겠습니다!
- debounce를 통해 검색이 끝나고 0.3초 뒤에 검색 필터링이 자동 적용되게 구현하였습니다.
=> [FE][BOM-135] feat: article search 기능 추가

.gitignore, frontend/buildspec.yml
- cd 파이프라인 구축
https://velog.io/@badahertz52/AWS-CodePipeline%EC%9D%84-%ED%86%B5%ED%95%9C-CD-%EA%B5%AC%EC%B6%95
=> [FE][BOM-97] feat: frontend cd 빌드 파일 추가

frontend/src/apis/articles.ts, frontend/src/apis/members.ts, frontend/src/routes/articles.$articleId.tsx, frontend/src/routes/index.tsx, frontend/src/routes/storage.tsx
=> [FE][BOM-163] chore: memeberId 제거

frontend/src/apis/auth.ts, frontend/src/apis/fetcher.ts, frontend/src/apis/members.ts, frontend/src/components/Header/Header.tsx, frontend/src/pages/signup/components/SignupCard.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes/articles.$articleId.tsx, frontend/src/routes/index.tsx, frontend/src/routes/signup.tsx, frontend/src/routes/storage.tsx
=> [FE][BOM-167] feat: signup 기능 구현

frontend/src/components/Header/Header.tsx
=> feat: 이메일 복사 시 alert

frontend/src/main.tsx, frontend/src/routes/__root.tsx, frontend/src/routes/_bombom.tsx
- 봄봄 페이지(로그인, 로그아웃 페이지 제외)에서만 beforeLoad가 적용되게 수정
=> [FE][BOM-185] feat: login routing 기능 수정

frontend/src/routeTree.gen.ts
=> [FE][BOM-193] fix: route tree 오류 해결

frontend/src/utils/math.ts
=> [FE][BOM-198] fix: 읽기 현황 컴포넌트에서 에러가 발생하는 현상 수정

frontend/src/apis/articles.ts, frontend/src/apis/fetcher.ts, frontend/src/hooks/useDebouncedValue.ts, frontend/src/routes/_bombom/storage.tsx
- 현재 검색을 하면 아티클은 필터링되지만, 왼쪽에 있는 카테고리 개수는 반영되지 않는다.
- 해당 오류를 보완하는 작업을 진행했다.
- 함수를 디바운싱하는 것이 아니라, searchInput 값을 디바운싱하는 방식으로 변경하였습니다.
- 확인 부탁드립니다~!
=> [FE][BOM-187] feat: 검색 결과에 따른 category 개수 업데이트

frontend/.vscode/settings.json, frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx, frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCard.tsx, frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCardSkeleton.tsx, frontend/src/routes/_bombom/index.tsx
[읽기 현황 데이터가 없을 때]
[읽기 현황 데이터가 로딩 중일 때]
- 컴포넌트 분리 및 로딩 처리를 진행하였습니다.
- 읽기 현황 스켈레톤을 구현하였습니다.
=> [FE][BOM-188] feat: today page loading 처리 및 리팩토링

frontend/src/routeTree.gen.ts, frontend/webpack.config.ts
=> [FE][BOM-204] chore: routeTree.gen.ts 세미클론 스타일 충돌 이슈

frontend/src/hooks/useScrollThreshold.ts, frontend/src/hooks/useScrollTrigger.ts, frontend/src/routes/_bombom/articles.$articleId.tsx, frontend/src/utils/scroll.ts
- 아티클 내용이 짧아 스크롤이 없을 경우 바로 읽음 처리 기능 구현
- 처음 로드 시, 스크롤이 없는지 판단한다.
- 초기 데이터가 없을 경우에도 스크롤이 없다고 판단하여, 데이터가 왔을 때 & 스크롤이 없을 때 읽음 처리한다.
=> [FE][BOM-189] fix: 스크롤이 없을 경우 바로 읽음 처리

.github/workflows/chromatic.yml
- 스토리북이 변경될 때마다 자동으로 빌드 및 배포되도록 깃허브 액션 추가
- 매번 배포 명령어를 실행하기 번거로움
- frontend 디렉터리에 push될 때마다 스토리북이 자동으로 재빌드되어 배포되도록 설정했습니다.
- 다음의 경로 혹은 파일이 변동될 때 실행됩니다.
- `frontend/src/**/*.{tsx,ts}`
- `frontend/.storybook/**`
- 파일은 공식문서를 참고했습니다. [(출처)](https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/)
=> [FE][BOM-174] chore: 스토리북 빌드 및 배포 자동화

frontend/src/routes/_bombom/storage.tsx
=> hotfix: 보관함 안보임 이슈

.github/workflows/dev-deploy.yml, backend/bom-bom-server/docker-compose-dev.yml
Docker compose 파일을 개발 전용으로 분리
개발환경과 운영환경 분리
- `docker-compose.yml` -> `docker-compose-dev.yml` 이름 변경
=> [BE][BOM-195] chore: 개발용 Docker Compse 분리

.github/workflows/dev-deploy.yml
Querydsl 도입 후 클린 빌드를 위해 수정했습니다.
=> dev-deploy.yml 수정

backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/NewsletterDetail.java, backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
NewsletterDetail에 발신자 필드를 추가했습니다.
=> [BE][BOM-208] feat: NewsletterDetail에 발신자 필드 추가

frontend/src/apis/env.ts, frontend/src/pages/login/components/LoginCard.tsx
- login queryString에 env=local을 추가해줬습니다.
=> [FE][BOM-216] feat: 로컬에서 로그인 시, 로컬로 redirect되게 수정

frontend/src/apis/env.ts, frontend/src/pages/login/components/LoginCard.tsx
- 본 서버에서 로그인 시, 개발 서버에서 로그인 되는 문제 수정
- client-dev 생성 시점과 커밋 기록이 꼬인 것으로 추정
- Login 버튼의 클릭 핸들러에 하드코딩된 개발 서버 api의 주소를 수정함.
=> [FE][BOM-232] hotfix: 본 서버에서 로그인 시, 개발 서버에서 로그인 되는 문제 수정

backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/dto/response/BookmarkResponse.java, backend/bom-bom-server/src/test/java/me/bombom/api/v1/bookmark/service/BookmarkServiceTest.java
- 북마크 dto 평탄화
- 프론트 요청
dto 평탄화작업을 진행
=>  [BE][BOM-244] refactor: 북마크 dto 평탄화

frontend/src/routes/_bombom/storage.tsx
=> [FE][BOM-249] chore: 페이지네이션 size page 수정

frontend/src/pages/detail/components/ArticleContent/ArticleContent.tsx
startNode가 없거나 endNode가 없을 경우 throw하는 error를 catch하는 곳이 없어서 웹사이트가 죽는 이슈가 있었습니다. ErrorBoundary로 감싼다고 하더라도, 다른 대체 ui를 보여주는 것도 어색하다고 생각하여, try-catch 로 감싸 해결했습니다.
=> [FE][BOM-248] fix: 변환 실패 시 터지는 이슈

frontend/src/apis/articles.ts, frontend/src/routes/_bombom/storage.tsx
=> [FE][BOM-250] fix: 정렬 안되는 이슈

frontend/src/components/Button/Button.tsx, frontend/src/components/PetCard/PetCard.tsx, frontend/src/types/openapi.d.ts
=> [FE][BOM-252] feat: 키우기 버튼 disabled

backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Pet.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Stage.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/StageRepository.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java, backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java, backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/event/AddArticleScoreListenerTest.java, backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/service/PetServiceTest.java
레벨업을 위해
PetService에서 increaseCurrentScore시에 requiredScore 범위에 알맞는 stage로 갱신하도록 구현
- 메서드명이 적절한지
- 트랜잭션 분리를 하다보니 테스트를 끼워 맞춰서 돌린 느낌이 있는데, 개선 방법 있으면 추천 부탁드립니다...
=> [BE][BOM-253] feat: 레벨업(score 갱신 시 stage 함께 갱신)

frontend/src/routes/_bombom/storage.tsx
https://github.com/user-attachments/assets/01f3a666-c5fd-4044-823b-58c17eb3633c
=> [FE][BOM-251] fix: 페이지 전체 깜빡임 이슈

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Pet.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Stage.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/PetRepository.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/event/UpdateReadingCountEvent.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/event/UpdateReadingCountListener.java, backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/event/UpdateReadingCountListenerTest.java
Reading 정보 업데이트 할 때 memberId를 빼고 전달중이었네요 하하
=> [BE][BOM-262] 잘못 전달하는 ID 수정

backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
아티클 조회 페이지네이션 getTotal을 수정했습니다.
페이지네이션 오류
=> [BE][BOM-259] fix: 아티클 조회 페이지네이션 getTotal 수정

frontend/src/components/PetCard/PetCard.tsx
=> [FE][Bom-263] fix: 키우기 이미지 안나오는 오류

frontend/src/components/PetCard/PetCard.tsx, frontend/src/pages/detail/components/MemoCard/MemoCard.tsx, frontend/src/routes/_bombom/memo.tsx
=> [FE][Bom-264] feat: 메모 모아보기 클릭 시 아티클 페이지로

frontend/src/libs/googleAnalytics/GAInitializer.tsx, frontend/src/libs/googleAnalytics/initGA.ts
=> [FE][BOM-267] fix: GA 오류 수정

frontend/src/pages/detail/components/ArticleBody/ArticleBody.tsx, frontend/src/pages/detail/utils/highlight.ts
=> hotfix: 하이라이트 안되는 이슈

frontend/src/routes/_bombom/storage.tsx
1. `총 개수`를 articles의 데이터로 수정했습니다.
2. 읽음/읽지않음 개수를 잘못 보내주고 있어, 어제 회의 때 논의한 대로 우선 제거했습니다. 서버에서 수정 시 다시 추가하면 좋을 거 같습니다.
=> [FE][BOM-268] fix: 총 개수 수정

.github/workflows/setup-opened-pr.yml
PR 제목에 따라 백엔드 / 프론트엔드 각각의 채널에 알림이 전송됩니다.
=> 슬랙봇 개선 : PR 제목에 따라 백엔드 / 프론트엔드 각각의 채널에 알림이 전송

frontend/package.json
찾아보니, 직접 JSON > YAML 변환 > 저장하지 않아도, /v3/api-docs url을 전달하면 알아서 타입 생성이 된다고 하더라구요..!
=> feat: openapi typescript 과정 축약

frontend/src/constants/device.ts, frontend/src/hooks/useDeviceType.ts, frontend/src/hooks/useMediaQuery.ts
- 제거할 부분이 있는지 아니면 현재 훅을 공용 훅으로 두고, 저희 서비스에 맞는 훅을 이것을 이용해서 만들면 좋을지 알려주시면 감사하겠습니다~!
=> [FE][BOM-284] feat: useMediaQuery 훅

frontend/src/components/Header/Header.tsx, frontend/src/components/Header/HeaderLogo.tsx, frontend/src/components/Header/HeaderNavButtons.tsx, frontend/src/components/Header/HeaderProfile.tsx, frontend/src/styles/theme.ts
https://github.com/user-attachments/assets/92dc54c1-d3c8-4aa5-bd22-b215dca4738a
- HeaderNavButtons, HeaderLogo, HeaderProfile 컴포넌트를 분리하였습니다.
- useDeviceType 훅을 통해서 deviceType 별로 스타일을 다르게 주는 방식으로 진행하였습니다.
=> [FE][BOM-277] refactor: 헤더 반응형 적용

frontend/src/apis/members.ts, frontend/src/apis/queries.ts, frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
=> [FE][BOM-330] 연령별 인기 뉴스레터 API 연결

frontend/src/components/PageLayout/PageLayout.tsx, frontend/src/types/nav.ts
=> [FE][BOM-370] 읽기 페이지에서 새로고침 시 네비게이션이 오늘의 뉴스레터로 고정되는 문제 해결

frontend/src/components/Pagination/Pagination.utils.ts
=> [FE][BOM-368] 페이지네이션에서 마지막 페이지가 추가되는 이슈

frontend/src/hooks/useScrollRestoration.ts, frontend/src/routes/_bombom/articles.$articleId.tsx
- 아티클 데이터가 있을 때 훅이 실행되도록 수정하였습니다.
=> [FE][BOM-331] 새로고침 스크롤 미복원 이슈 해결

frontend/src/components/PetCard/PetCard.tsx
=> [FE][BOM-376] 펫 비율 꺠짐 현상

backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/event/MarkAsReadListenerTest.java
오늘의 아티클을 읽은 경우에만 펫 점수 올리는 것에서 테스트를 수정했습니다.
=> hotfix: 오늘 도착한 아티클의 경우만 펫 점수 올라가는 테스트 작성 및 수정

.github/workflows/server-prod-rollback.yml
[운영 서버 버저닝 도입 PR](https://github.com/woowacourse-teams/2025-bom-bom/pull/254)을 먼저 확인하고 오시면 좋습니다!
**⚠️ `main` 브랜치에 직속 merge 되는 PR입니다!**
운영 서버의 간편한 롤백을 위해 롤백 워크플로우를 구축합니다.
추후 운영 서버 배포 시 치명적인 상황에 대한 대응을 위함입니다.
- 버저닝 및 롤백에 관련된 상세한 사항은 [롤백 시스템 구축하기](https://meadow-technician-018.notion.site/254b4854680e80fa8cecfd12571712df)에 문서화 해두었습니다. 참고 부탁드립니다!
- DB 관련된 핀포인트 롤백은 실제로 자주 일어나지 않고, 정합성이 깨지는 문제가 발생하지 않는 이상 잘 하지 않는다고 하더라구요. 
- 그래서 일단 이번 롤백에서는 서비스 코드 레벨의 롤백만 고려했습니다.
- 버저닝과 롤백 구축은 처음 해본지라 이렇게 하는게 맞는지 잘 모르겠습니다..! 피드백 부탁드려요!
- 헬스체크 파트가 필요할 것 같다고 생각해서 넣긴 했는데, 저 커맨드로 헬스체크가 정상 작동 하지 않는 것 같습니다 ㅜ 혹시 유추되는 원인이 있는 분 계시다면 알려주심 감사하겠습니다!
- 헬스체크 실패해도 강제 롤백되도록 설정해서 롤백 테스트 진행 해봤었는데, 헬스체크는 실패해도 서비스는 정상적으로 롤백 되고 실행도 잘 되더라구요.. 어떻게 해야할까요?
=> [BE][BOM-337] chore: 운영 서버 롤백 워크플로우 구축

backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
회원가입 시 birthDate 필드 추가했습니다.
DB에 생년월일이 안들어가고 있었습니다..
회원가입 서비스 메서드에서 만들어지는 빌더에 birthDate 필드를 추가했습니다.
=> [BE][BOM-390] fix: 회원가입 시 birthDate 필드 추가

frontend/src/pages/detail/components/FloatingToolbar/useFloatingToolbarSelection.ts
- 태블릿일 때 플로팅 툴바를 아래로 위치를 변경하였습니다.
=> [FE][BOM-398] ipad 하이라이트 플로팅 툴바 위치 변경

frontend/src/pages/detail/components/FloatingToolbar/useFloatingToolbarSelection.ts
=> refactor: 태블릿일 때도 FloatingToolbar 위치 하단으로 (#293)

frontend/src/components/PageTitle/PageTitle.ts, frontend/src/libs/googleAnalytics/initGA.ts
=> [FE][BOM-414] GA 추가 설정

app/.prettierrc, app/app.json, app/ios/Podfile.properties.json, app/ios/app.xcodeproj/project.pbxproj, app/ios/app/Info.plist, app/package-lock.json, app/package.json, frontend/src/components/Modal/useModal.ts
- 이전에 진행했던 앱 이름 변경 작업을 빌드/TestFlight 배포만 하고 client-dev에 pr을 안올렸네요..
=> [FE][BOM-410] expo 앱 이름 변경

frontend/src/pages/signup/components/SignupCard.tsx, frontend/src/pages/signup/components/SignupCard.types.ts, frontend/src/pages/signup/components/SignupCard.utils.ts, frontend/src/styles/theme.ts, frontend/src/types/openapi.d.ts
- 회원가입 시, 생년월일 및 성별을 옵셔널로 받도록 수정
<br>
[필수 값만 입력]
<br>
[필수 값 입력 X]
- 앱 배포 심사 요구사항 충족 목적
- 핵심 기능에 사용되지 않는 개인정보는 옵셔널로 받아야 한다.
- gender, birthdate 데이터를 옵셔널로 수정
- 필수로 받아야 하는 정보 field에 * 추가
=> [FE][BOM-426] 회원 가입 정보를 옵셔널로 변경

backend/bom-bom-server/build.gradle.kts, backend/bom-bom-server/src/main/java/me/bombom/BomBomServerApplication.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthControllerApi.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/request/NativeLoginRequest.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/handler/OAuth2LoginSuccessHandler.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/AppleOAuth2Service.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/IdTokenValidator.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SecurityConfig.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/ShedLockConfig.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/TodayReadingRepository.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/WeeklyReadingRepository.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/scheduler/ReadingScheduler.java, backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java, backend/bom-bom-server/src/main/resources/db/migration/V3.00__create_shedlock_table.sql
=> DEV -> PROD

backend/bom-bom-server/src/main/resources/db/migration/V4.0.0_create_newsletter_verification.sql
이메일 서버 뉴스레터 인증 메일 로직 추가로 DB 적용을 위해 테이블 추가
이거 없으면 터짐
`newsletter_verification` 스키마 추가
- newsletterEmail에 유니크를 걸지 않은 이유
- 같은 회사에서 발행한 서로다른 뉴스레터가 같은 인증 메일을 쓸 수도 있기 때문에
=> [BE][BOM-447] 뉴스레터 인증 메일 테이블 추가

frontend/src/hooks/useDebounce.ts, frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx, frontend/src/pages/detail/hooks/useArticleBookmark.ts, frontend/src/routes/_bombom/articles.$articleId.tsx
- `cancelOnUnmount?: boolean;`라는 옵션을 추가해서
- cancelOnUnmount: false를 하면 언마운트 되어도 setTimeout에 등록한 콜백이 실행되도록 처리하였습니다.
=> [FE][BOM-438] 북마크 낙관적 업데이트에서 useDebounce 클린업 함수 제거 옵션 추가

frontend/src/libs/webview/webview.utils.ts, frontend/src/pages/login/components/LoginCard.tsx
- 웹에서 애플 로그인이 보이도록 수정
웹 환경에서 애플 로그인 버튼이 보이지 않음
=> [FE][BOM-497] 웹에서 애플 로그인 버튼이 사라진 문제 수정

frontend/src/routes/login.tsx
=> feat: 로그인 실패 처리

frontend/src/routes/login.tsx
=> feat: 로그인 실패 처리 (#388)

frontend/CLAUDE.md
=> [FE][BOM-514] frontend 팀 공통 CLADUE.md 작성

app/app/_layout.tsx, app/app/index.tsx, app/plugins/withNetworkSecurityConfigFile.js
1. `withNetworkSecurityConfigFile.js`의 xml코드를 제거해서 네트워크 에러를 해결합니다.
2. index.tsx 파일을 추가해서 루트 파일을 추가합니다.
=> [FE][BOM-516] 안드로이드 빌드 이슈 해결

app/utils/auth.ts, frontend/src/apis/auth.ts, frontend/src/libs/webview/useWebViewAuth.ts, frontend/src/types/openapi.d.ts
=> [FE][BOM-534] chore: 회원가입 api 변경사항 반영

frontend/index.html, frontend/src/styles/reset.ts
앱같은 웹 경험을 위해 핀치 줌을 방지합니다.
1. `minimum-scale=1.0` : 사용자가 축소할 수 있는 최소 비율 설정
2. user-scalable=no : 핀치 줌(확대/축소) 기능 비활성화
3. `touch-action: pan-x pan-y` : 터치 스크린에서 허용할 터치 제스쳐의 종류 지정
- iOS에서는 핀치줌을 막기 위해 이 설정이 필요합니다.
- 테스트 방법 : npm run start> 동일한 인터넷의 모바일 기기로 ip주소로 접속
=> [FE][BOM-542] chore: 터치 디바이스 핀치 줌 방지
